### ISSUE TITLE
Make charts responsive

### ISSUE THREAD

**Issue by sir-dunxalot** [sir-dunxalot/ember-google-charts#1]
When the window resizes, use `chart.draw()` the change the size and make the graphs responsive.

Responsiveness should probably be an optional feature that defaults to `true`.

**Comment by Turbo87** [comment]
I guess https://www.npmjs.com/package/ember-resize would be useful for this

**Comment by sir-dunxalot** [comment]
Nice, thanks for the heads up.

**Comment by jhonandres21** [comment]
Still need help on this? I'm interested.

**Comment by sir-dunxalot** [comment]
Yeah, a PR would be great as this isn't a priority for me right now. Let me know what info I can provide if you're able to dig into it.

**Comment by sir-dunxalot** [comment]
Fixed by #28.
