### ISSUE TITLE
Can't use with a ajax.

### ISSUE THREAD

**Issue by flpms** [sir-dunxalot/ember-google-charts#13]
Hi,

This module is great, but I can't use it inside with data is fulfilled after the model is ready.

**Comment by sir-dunxalot** [comment]
Do you mean like using a promise? Are you changing the model or adding records to it?

Compatibility with promises should have been added with `0.1.2`.

**Comment by flpms** [comment]
Yes. I need promise. I'm look for this improvement then.

**Comment by sir-dunxalot** [comment]
I believe this has been fixed but if not let me know and I will reopen this issue.
