### ISSUE TITLE
Listening for events?

### ISSUE THREAD

**Issue by denchen** [sir-dunxalot/ember-google-charts#26]
Does this repo have support for creating your own custom handlers for specific events? The ones I'm most interested in are `onmouseover` and `onmouseout` as detailed in the [Interacting With the Chart](https://developers.google.com/chart/interactive/docs/basic_interactivity) section of the Google docs.

I was hoping to be able to define a custom event very similar to how the [React Google Charts library](https://github.com/RakanNimer/react-google-charts#listen-to-chart-events) does it.

**Comment by denchen** [comment]
Actually, I belatedly realized I could've just used the Google API to do what I need. So in my case, I want to listen for `mouseover` and `mouseout`, what I have is:

Template:

    {{pie-chart data=data options=options chartDidRender='afterRender'}}

Component:

    actions: {
      afterRender(chart) {
        let { visualization } = window.google;
        visualization.events.addListener(chart, 'onmouseover', function(event) {
          console.log('Mouseover heard:', event);
          // The above prints something like: Object { row: 2, column: null }
        });
      }
    }

The key was I didn't realize I had access to the `window.google.visualization` object.

**Comment by sir-dunxalot** [comment]
Sounds like a feature is not needed here but it's a good issue to have for other who might come across this issue?

**Comment by denchen** [comment]
I think perhaps a small section in the README would be nice on how to handle events?

**Comment by sir-dunxalot** [comment]
Sounds good! I'll leave this issue open as a reminder until I can get round to it.
