### ISSUE TITLE
visualization[visualizationName] is not a constructor / Container is not defined

### ISSUE THREAD

**Issue by denchen** [sir-dunxalot/ember-google-charts#30]
I have a rather complex app that can have several Google charts on a single page. But often, I see this in my console:

<img width="1120" alt="screenshot 2016-11-09 19 11 16" src="https://cloud.githubusercontent.com/assets/2073768/20163329/77f44abe-a6b0-11e6-831a-92879f8688ef.png">

My app is rather complex, so I'm not sure how much code I would need to post for you to get a good idea of what's going on, nor am I sure I can pare my app down to a reproducible snippet, so what I'm asking is, can you think of any general reasons why this would occur? Or at least, is there a way to debug this to find the source of (most likely) my mistake? I'm currently on **1.5.0**.

**Comment by denchen** [comment]
Going through my code and the code in this repo, this is what I **think** may be happening.

I defer the loading of my chart data until after the page is rendered. So in the initial render of my page, I have an `{{#if chartData}}`, and if there is no data, I create an "empty" chart (something with just an X- & Y-axis and not much else). After the data is loaded, the template is re-rendered, and a new chart with the data is rendered. I say 75% of the time, this logic works.

However, I think it's possible that loading of my chart data completes before the loading of the Google Charts library (for my initial empty chart) completes, and when the template re-renders and the chart components are called, it gets into a weird state where `loadPackages()` thinks Google Charts is already loaded -- via the check for `window.google.visualization` -- when it really hasn't. Thus what I see happening is that `_renderChart()` gets called before the `google.charts.load` callback does.

In fact I put this code in https://github.com/sir-dunxalot/ember-google-charts/blob/d5651d461b9dbb28190bced740c460d720bf9e92/addon/components/google-chart.js#L120-L128 to test my theory:

    if (window.google.visualization) {
      console.debug('google.visualization exists');
    } else {
      console.debug('google.visualization DOES NOT exist');
    }
    if (window.google.visualization.AreaChart) {
      console.debug('AreaChart exists');
    } else {
      console.debug('AreaChart DOES NOT exist');
    }

And when I do get failures, my console shows:

    google.visualization exists
    AreaChart DOES NOT exist

Of course, when things do go right I get:

    google.visualization exists
    AreaChart exists    

So I believe a check for `window.google.visualization` may not be enough to validate Google Charts has loaded properly.

**Comment by denchen** [comment]
One last note. I followed the instructions in the README for customizing the `google-charts` service and overrode `loadPackages()` by modifying just [this single line](https://github.com/sir-dunxalot/ember-google-charts/blob/master/addon/services/google-charts.js#L14) to:

    let wasPreviouslyLoadedInTestSuite = google && google.visualization && google.visualization.CoreChart;

And I was able to get rid of all the `visualization[visualizationName] is not a constructor` errors. I'm not sure if this is actually a good way to ensure the visualization library is loaded, but it does work for my use case. If you think this is a valid solution, I could create a pull request.

However, I was not able to get rid of the `Error: Container is not defined` errors, but I believe these are of less importance. My *best guess* is that a chart is trying to render to a DOM element that was removed in the time it took for the visualization library to load. If this is the case, I don't see this as a critical error, though it would be nice to have this edge case addressed at some point.

**Comment by pomm0** [comment]
I'm facing this error too. Any news?

**Comment by sir-dunxalot** [comment]
Am tidying up some old issues in this repo.

I have not been able to reproduce (nor consistently reproduce) this issue. My recommendation, therefore, is to avoid wrapping a chart in `{{#if chartData}}` and instead let `chartData` automatically re-render the chart as [this demo example](http://sir-dunxalot.github.io/ember-google-charts/#/promises) illustrates.

For example:

```hbs
{{#if chartData}}
  {{area-chart data=chartData options=options}}
{{/if}}
```

should become:

```hbs
{{area-chart data=chartData options=options}}
```
