### ISSUE TITLE
how to obtain data from json file

### ISSUE THREAD

**Issue by JEEVANJGA** [sir-dunxalot/ember-google-charts#32]
how to pass data from a json file?

route Js file:-

>  import Ember from 'ember':
export default Ember.Route.extend({
	model(){
		return Ember.$.get('/dashboardstore/employee-country.json');
	}
});

template hbs file:

> {{log model}}

	<br>
	<table style="border:1px solid black">
		<tr > 
			<th style="border:1px solid black">country</th><th style="border:1px solid black">Employee count</th>
		</tr>
		{{#each model as |item|}}
				  <tr >
				  		<td style="border:1px solid black">{{item.company_location}}</td>
				  		<td style="border:1px solid black">{{item.employee_count}}</td>
				  </tr>
		{{/each}}
	</table>
{{outlet}}

json file i tried to use:

`[{
  "company_location": "Mexico",
  "employee_count": 60
}, {
  "company_location": "Russia",
  "employee_count": 343
}, {
  "company_location": "Poland",
  "employee_count": 491
}, {
  "company_location": "United Arab Emirates",
  "employee_count": 85
}, {
  "company_location": "Philippines",
  "employee_count": 310
}, {
  "company_location": "Yemen",
  "employee_count": 99
}, {
  "company_location": "Portugal",
  "employee_count": 466
}, {
  "company_location": "Greece",
  "employee_count": 437
}, {
  "company_location": "Colombia",
  "employee_count": 285
}, {
  "company_location": "Iran",
  "employee_count": 306
}]`

how should be model defined in the Js file so that to get output in the template

**Comment by sir-dunxalot** [comment]
The best guidance I can provide is to read the Google Charts documentation to understand the format you need to pass data to your chart in.

Specifically, you can pass `data` to any chart component as a [Google DataTable](https://developers.google.com/chart/interactive/docs/datatables_dataviews) or any array that can be passed to [arrayToDataTable()](https://developers.google.com/chart/interactive/docs/datatables_dataviews#arraytodatatable).

**Comment by sir-dunxalot** [comment]
You might also find [preparing the data](https://developers.google.com/chart/interactive/docs/basic_preparing_data) to be a helpful guide.
