### ISSUE TITLE
l.arrayToDataTable is not a function

### ISSUE THREAD

**Issue by irenliber** [sir-dunxalot/ember-google-charts#33]
How can I avoid an error "l.arrayToDataTable is not a function"? It occurs sometimes
when I load page with line-chart component. Chart isn't rendered
![error](https://cloud.githubusercontent.com/assets/18288936/23071010/896f4106-f55f-11e6-9bfe-a92422df13e4.png)

**Comment by sir-dunxalot** [comment]
Thank you for reporting the issue. I haven't observed this issue 'in the wild' or been able to reproduce it.

If this is still a problem, please could you share a reproducible example or point me in the right direction.
