### ISSUE TITLE
Data roles not working

### ISSUE THREAD

**Issue by andrewcallahan** [sir-dunxalot/ember-google-charts#34]
Following the [example bar chart](https://sir-dunxalot.github.io/ember-google-charts/chart-types/bar), the data is set in the router:
```
import Ember from 'ember';

export default Ember.Route.extend({

  model() {
    return [
      ['Element', 'Density', { role: 'style' }],
      ['Copper', 8.94, '#b87333'],
      ['Silver', 10.49, 'silver'],
      ['Gold', 19.30, 'gold'],
      ['Platinum', 21.45, 'color: #e5e4e2'],
    ];
  },

});
```

Then it is passed into the bar-chart component
```
{{bar-chart data=model options=options}}
```

However, the colors are not coming through on the bar chart. Also, when I tried adding annotation data by adding a `{ role: 'annotation' }`, it similarly is not coming through.

Thoughts?

**Comment by lauraannwilliams** [comment]
This gem defaults to material bar charts, which don't support coloring the bars.

**Comment by sir-dunxalot** [comment]
As @lauraannwilliams has pointed out, this is an issue with Google Charts and not this addon.
