### ISSUE TITLE
Custom Charts Example in Readme is confusing

### ISSUE THREAD

**Issue by brendanoh** [sir-dunxalot/ember-google-charts#38]
The Gantt chart type cannot be rendered by the Material renderer so if you take the "example" code and think it will work you will get very frustrated.

The example should probably be changed to show the classic renderer and perhaps even provide a link to a place to find the list of which charts are available in the material renderer. Unfortunately that only seems available in the [Release Notes](https://developers.google.com/chart/interactive/docs/release_notes) by searching for 'material'.

**Comment by sir-dunxalot** [comment]
Good feedback. Fixed by #52.
