### ISSUE TITLE
ember-cli-babel deprecation

### ISSUE THREAD

**Issue by rmachielse** [sir-dunxalot/ember-google-charts#46]
This addon is still using `ember-cli-babel@5`, which is now deprecated.
Would a pr upgrading that and other dependencies be desired?

**Comment by rmachielse** [comment]
@sir-dunxalot are you interested in a pr for this?

**Comment by sir-dunxalot** [comment]
@rmachielse Yes, definitely interested in a PR. I will be catching up with this library to make it better maintained and up-to-date soon. I would love to merge in a PR for this during that process.

**Comment by rmachielse** [comment]
@sir-dunxalot I tried to upgrade `ember-cli-babel`, but the tests don't seem to work anymore on master. I think an upgrade of `ember-cli` and dependencies is needed
