### ISSUE TITLE
Legend not rendering in ember-google-charts geochart

### ISSUE THREAD

**Issue by BBK-SDP-2015-jtomli03** [sir-dunxalot/ember-google-charts#5]
Hi, I've noticed that this isn't rendering on the ember-google-charts geochart page either; 
http://sir-dunxalot.github.io/ember-google-charts/chart-types/geo
Is this an issue that needs resolving or is it just something I'm missing?
Thanks,
Jo

**Comment by sir-dunxalot** [comment]
Looking at the [Google geo chart docs](https://developers.google.com/chart/interactive/docs/gallery/geochart), it looks like the legend should render by default. This looks like a bug so I'll investigate when I can but would be happy to accept a PR for this issue too.
