### ISSUE TITLE
Chart not re-rendering

### ISSUE THREAD

**Issue by ptmoy2** [sir-dunxalot/ember-google-charts#6]
I'm trying to make an area chart by using:  {{area-chart data=myData}}

'myData' is an Ember computed property tied to several other properties.  When 'myData' changes, I thought the chart was going to automatically update; it does not.  Do I need to set some option explicitly to make this happen?

**Comment by sir-dunxalot** [comment]
This functionality isn't currently built but it won't be too hard. In fact, it's the next thing I have planned for this addon. The way I've been envisioning this feature (using the `didReceiveAttrs` component hook) would only support Ember 1.13+. Would that be a problem for you?

**Comment by ptmoy2** [comment]
Thanks for your comments.  I'm using Ember 2.2, so that wouldn't be a problem.  I have an app that's currently using this addon: https://github.com/Glavin001/ember-c3, which is a wrapper over C3js.  C3js is built using D3.  It does automatic re-rendering and more, but it's really slow in my application for some reason.  I'm hoping Google chart would perform a bit better.  You may want to take a look at how they interfaced to Ember.

**Comment by sir-dunxalot** [comment]
Sounds good - thanks for the tip! I will keep this thread updated.

**Comment by sir-dunxalot** [comment]
Fixed by 1.2.0
