### ISSUE TITLE
IE11 Object doesn't support property or method 'contains'

### ISSUE THREAD

**Issue by JoshMesser** [sir-dunxalot/ember-google-charts#7]
I have a page that allows users to render a data set with different chart types.

```
{{#if showCharts}}
	<center>
		{{#if chartOptions.bar}}
			{{bar-chart data=dataForCharts.data options=dataForCharts.options}}
		{{/if}}
		{{#if chartOptions.pie}}
			{{pie-chart data=dataForCharts.data options=dataForCharts.options}}
		{{/if}}
		{{#if chartOptions.geo}}
			{{geo-chart data=dataForCharts.data options=dataForCharts.options}}
		{{/if}}
	</center>
{{/if}}
```

This is contained within' a larger tab selection that changes the data sent to the charts.

When the larger tab selection is changed I hide the charts `showCharts` then update `dataForCharts` and show the charts again. I do it this way so the chart component fires the `destroy` event and the chart can be broken down. This works great in every browser but IE11. In IE11 I get text that says `Object doesn't support property or method 'contains'`.

I know this has something to do with chart instances being destroyed and recreated. The suggested solution is to reuse the same chart instance, I don't see how that's a option using `ember-google-charts` unless I rewrite large parts of it. Any suggestions?

**Comment by sir-dunxalot** [comment]
Thanks for opening the issue. I am working on a new release so we can hopefully include a fix for this in the release.

Can you provide a stack trace please? I was not able to find `contains` anywhere in this repo.

**Comment by JoshMesser** [comment]
Sadly there isn't a stack trace, the **error** comes from Charts itself. Just a small set of white text with a red background that reads `Object doesn't support property or method 'contains'`. You're right I too was unable to find `contains` anywhere, that's why I'm baffled.

**Comment by sir-dunxalot** [comment]
Got it. It could be related to this issue: https://github.com/google/google-visualization-issues/issues/2039

It doesn't appear there is anything to be fixed in this repo.
